# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-02 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default='Comment', max_length=200),
        ),
    ]
